SRC_NAME = gecoac
THISDIR = $(shell pwd)

all: 

config_test:

configure:

clean:

romfs:
	$(ROMFSINST) -p +x $(THISDIR)/gecoac /usr/bin/gecoac
	$(ROMFSINST) -p +x $(THISDIR)/gecoac.sh /usr/bin/gecoac.sh
