/* NX18N */

#define BOARD_PID		"NX18N"
#define BOARD_NAME		"NX18N"
#define BOARD_DESC		"NX18N Wireless Router"
#define BOARD_VENDOR_NAME	"H3C"
#define BOARD_VENDOR_URL	"http://www.h3c.com.cn/cn/"
#define BOARD_MODEL_URL		"http://www.h3c.com.cn/cn/"
#define BOARD_BOOT_TIME		30
#define BOARD_FLASH_TIME	120
#define BOARD_GPIO_BTN_RESET	3
#define  BOARD_GPIO_BTN_WPS	12
#undef  BOARD_GPIO_LED_ALL
#undef  BOARD_GPIO_LED_WIFI
#undef  BOARD_GPIO_LED_SW2G
#undef  BOARD_GPIO_LED_SW5G
#define BOARD_GPIO_LED_POWER	15
#undef  BOARD_GPIO_LED_LAN
#define BOARD_GPIO_LED_WAN	16
#define BOARD_GPIO_LED_USB	8
#define BOARD_GPIO_LED_ROUTER	
#undef  BOARD_GPIO_PWR_USB
#define BOARD_HAS_5G_11AC	0
#define BOARD_NUM_ANT_5G_TX	0
#define BOARD_NUM_ANT_5G_RX	0
#define BOARD_NUM_ANT_2G_TX	0
#define BOARD_NUM_ANT_2G_RX	0
#define BOARD_NUM_ETH_LEDS	1
#define BOARD_HAS_EPHY_L1000	1
#define BOARD_HAS_EPHY_W1000	1
#define BOARD_NUM_UPHY_USB3	0
#define BOARD_USB_PORT_SWAP	0
